[project]
name = "kubrick_vector_database_layer"
version = "0.1.0"
description = "AWS Lambda Layer for database queries and transactions"
requires-python = ">=3.13"
dependencies = ["psycopg2-binary>=2.9.10"]
