[project]
name = "fetch-videos"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "boto3>=1.39.11",
    "twelvelabs>=0.4.11",
    "psycopg2-binary>=2.9.10",
]