[project]
name = "kubrick_embed_service_layer"
version = "0.1.0"
description = "AWS Lambda Layer for calling external multimodal embedding API"
requires-python = ">=3.13"
dependencies = ["twelvelabs>=1.0.0b0"]
