[project]
name = "response_utils_layer"
version = "0.1.0"
description = "AWS Lambda Layer for HTTP response utilities"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "boto3>=1.39.14",
]
